config/routes.rb
Rails.application.routes.draw do
  resources :subscription, only: [:update]

  resources :charges, only: [:new, :create]

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  get 'users/index'

	devise_for :users

	get 'blocipedia' => 'welcome#index'

	authenticated :user do
		root 'wikis#index', as: :authenticated_root
	end

	root 'welcome#index'

	mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
	belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
	has_many :wikis
	has_many :collaborators
	has_many :wiki_collaborations, through: :collaborators, source: :wiki
	after_initialize :init

	devise :database_authenticatable, :registerable, :confirmable,
				 :recoverable, :rememberable, :trackable, :validatable

  def init
    self.role  ||= :standard # will set the default value only if it's nil
	end

	enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ApplicationRecord
	belongs_to :user
	has_many :collaborators
	has_many :users, through: :collaborators, source: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit

	protect_from_forgery with: :exception

	before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount: 15_00
    }

  end

	def create
		# Creates a Stripe Customer object, for associating
		# with the charge
		customer = Stripe::Customer.create(
			email: current_user.email,
			card: params[:stripeToken]
		)

		# Where the real magic happens
		charge = Stripe::Charge.create(
			customer: customer.id, # Note -- this is NOT the user_id in your app
			amount: 15_00,
			description: "BigMoney Membership - #{current_user.email}",
			currency: 'usd'
		)

		current_user.role = 'premium'
		current_user.save

		flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
		redirect_to users_index_path(current_user) # or wherever

		# Stripe will send back CardErrors, with friendly messages
		# when something goes wrong.
		# This `rescue block` catches and displays those errors.
		rescue Stripe::CardError => e
			flash[:alert] = e.message
			redirect_to new_charge_path
	end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def update
    @wiki = Wiki.friendly.find(params[:wiki_id])
    authorize @wiki
    if @wiki.update(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki page. Please try again."
      render :edit
    end
  end

  def create
    user = User.find_by_email(params[:collaborator][:user])
    @wiki = Wiki.find(params[:wiki_id])
    if @wiki.users.include?(user)
      flash[:alert] = "#{user.email} has already been added as a collaborator"
      redirect_to edit_wiki_path(@wiki)
    else
      if Collaborator.create(user_id: user.id, wiki_id: @wiki.id)
        flash[:notice] = "#{user.email} is now a collaborator"
      else
        flash[:alert] = "#{user.email} was not added as a collaborator"
      end
      redirect_to edit_wiki_path(@wiki)
    end
  end

  def destroy
    user = User.find(params[:user_id])
    @wiki = Wiki.find(params[:wiki_id])
    collaborator = Collaborator.find_by(params[:user_id])
    if collaborator.destroy
      flash[:notice] = "Collaborator: #{collaborator.user.email} has been removed"
    else
      flash[:alert] = "Collaborator: #{collaborator.user.email} has not been removed"
    end
    redirect_to edit_wiki_path(@wiki)
  end
end

app/controllers/subscription_controller.rb
class SubscriptionController < ApplicationController
  def update
		current_user.role = 'standard'
		current_user.wikis.each do |wiki|
			wiki.update_attribute(:private, false)
		end
		current_user.save

		redirect_to edit_user_registration_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @user = current_user
    if @user.admin?
      @wikis = Wiki.all
    elsif @user.premium?
      @wikis = Wiki.where(private: false) | @user.wiki_collaborations | @user.wikis
    elsif @user.standard?
      @wikis = Wiki.where(private: false) | @user.wiki_collaborations
    else
      @wikis = Wiki.where(private: false)
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @user = current_user
    @wiki = Wiki.find(params[:id])
    @user_emails = User.where.not(id: current_user.id || @wiki.users.pluck(:id)).map(&:email)
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.update(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki page. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki page."
      render :show
    end
  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
		options = {
			filter_html:     true,
			hard_wrap:       true,
			link_attributes: { rel: 'nofollow', target: "_blank" },
			space_after_headers: true,
			fenced_code_blocks: true
		}

		extensions = {
			autolink:           true,
			superscript:        true,
			disable_indented_code_blocks: true
		}

		renderer = Redcarpet::Render::HTML.new(options)
		markdown = Redcarpet::Markdown.new(renderer, extensions = {})

		markdown.render(text).html_safe
	end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<h1>Charges#new</h1>
<p>Find me in app/views/charges/new.html.erb</p>

<%= form_tag charges_path do %>
	<h4>Click the button!</h4>
	<script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

		<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<div class="container">
			<div class="nav nav-tabs">
					<% if user_signed_in? %>
						<div class="pull-left">
							<%= link_to 'Wikis', wikis_path%>
						</div>
						<div class="pull-right">
							Signed in as: <strong><%= current_user.email %></strong> |
							<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
							-
							<%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
						</div>
					<% else %>
						<div class="pull-left">
							<%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
							<%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
						</div>
					<% end %>
			</div>

			<% if flash[:notice] %>
			 <div class="alert alert-success">
			   <button type="button" class="close" data-dismiss="alert">&times;</button>
			   <%= flash[:notice] %>
			 </div>
			<% elsif flash[:alert] %>
			 <div class="alert alert-warning">
			   <button type="button" class="close" data-dismiss="alert">&times;</button>
			   <%= flash[:alert] %>
			 </div>
			<% end %>

	    <%= yield %>
		</div>
  </body>
</html>

app/views/subscription/edit.html.erb
<h1>Subscription#edit</h1>
<p>Find me in app/views/subscription/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="container-fluid">
  <div class="row">
    <% if current_user.admin? || current_user.premium? %>
      <div class='field'>
        <%= form_for [@wiki, Collaborator.new] do |f| %>
          <%= f.label :collaborators %>
          <%= f.select :user, options_for_select(@user_emails, :selected => params[:user]) %>
          <%= f.submit 'Add', class: 'btn btn-secondary' %>
        <% end %>
        <% if @wiki.users.any? %>
          <h3>Current collaborators</h3>
          <% @wiki.users.each do |user| %>
            <p><%= user.email %>
            | <%= link_to "x", wiki_collaborator_path(user_id: @user.id, wiki_id: @wiki.id), method: :delete %>
          </p>
          <% end %>
        <% end %>
      </div>
    <% else %>
        <h3>Current collaborators</h3>
        <% @wiki.users.each do |user| %>
          <% if user.email == current_user.email %>
            <p><%= current_user.email %>
            | <%= link_to "x", wiki_collaborator_path(user_id: @user.id, wiki_id: @wiki.id), method: :delete %>
            </p>
          <% end %>
        <% end %>
    <% end %>
  </div>
</div>

<div class="row">
	<div class="col-md-4">
		<p>Guidelines for wikis</p>
		<ul>
			<li>Too many words 👎🏽</li>
		 	<li>Relates to its content 👍🏽</li>
		 	<li>SPAM = BAN 😡</li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= form_for @wiki do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
			</div>
			<div class="form-group">
				<%= f.label :body %>
				<%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
			</div>
			<% if current_user.admin? || current_user.premium? %>
			  <div class="form-group">
			    <%= f.label :private, class: 'checkbox' do %>
			      <%= f.check_box :private %> Private wiki
			    <% end %>
			  </div>
			<% end %>
			<div class="form-group">
				<%= f.submit "Save", class: 'btn btn-success' %>
			</div>
		<% end %>
	</div>
</div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<div class="row">
	<div class="col-md-8">
		<% @wikis.each do |wiki| %>
			<% if wiki.private == false %>
				<div class="media">
					<div class="media-body">
						<h4 class="media-heading">
							<%= link_to wiki.title, wiki %>
						</h4>
					</div>
				</div>
			<% elsif current_user == wiki.user || current_user.admin? %>
				<div class="media">
					<div class="media-body">
						<h4 class="media-heading">
							<%= link_to wiki.title, wiki %>
						</h4>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
	<div class="col-md-4">
		<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
	</div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
	<div class="col-md-4">
		<p>Guidelines for wikis</p>
		<ul>
		 	<li>Too many words 👎🏽</li>
		 	<li>Relates to its content 👍🏽</li>
		 	<li>SPAM = BAN 😡</li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= form_for @wiki do |f| %>
			<div class="form-group">
		   	<%= f.label :title %>
		   	<%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
		 	</div>
		 	<div class="form-group">
		   	<%= f.label :body %>
		   	<%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
		 	</div>
			<% if current_user.admin? || current_user.premium? %>
			  <div class="form-group">
			    <%= f.label :private, class: 'checkbox' do %>
			      <%= f.check_box :private %> Private wiki
			    <% end %>
			  </div>
			<% end %>
		 	<div class="form-group">
		   	<%= f.submit "Save", class: 'btn btn-success' %>
		 	</div>
	 	<% end %>
	</div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
	<div class="col-md-8">
		<p><%= markdown(@wiki.body) %></p>
	</div>
	<div class="col-md-4">
		<%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
		<%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
	</div>
</div>